config/routes.rb
Rails.application.routes.draw do
  # root "sessions#new"

  post 'direct_messages', to: 'direct_messages#create'
  resources :rooms
  resources :entries
  get 'events/work_hours', to: 'events#work_hours'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :work_schedules
  get 'works/edit', to: 'works#edit'
  patch 'works', to: 'works#update'
  # get 'works', to: "works#index"
  get 'works/data', to: 'works#data'
  get '/qrcode', to: 'qrcode#index'
  get 'cameras/index', to: 'cameras#index'
  get 'staffs/index'
  resources :users
  get 'events/index', to: 'events#index'
  get 'events/pickup', to: 'events#pickup'
  get 'events/received', to: 'events#received'

  get 'record_pdfs/index'

  get 'receiveds', to: 'receiveds#index'
  get 'receiveds/index_box', to: 'receiveds#index_box_in'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pickup_requests, only: %i[create update destroy]
  resources :receiveds, only: %i[create update destroy]
  post 'receiveds/update', to: 'receiveds#update'
  get '/receiveds/show', to: 'receiveds#show'
  get '/receveds/modify', to: 'receiveds#modify'
  get '/pdf', to: 'record_pdfs#index'
  get '/pickup_requests/index', to: 'pickup_requests#index'
  get 'pickup_requests/edit', to: 'pickup_requests#edit'
  post 'pickup_requests/create_received', to: 'pickup_requests#create_received'

  # ##########routes for react#############

  root to: redirect('/home')
  get '/home', to: 'site#index'
  get '/login_react', to: 'site#index'
  get '/dashboard', to: 'site#index'
  get '/works', to: 'site#index'

  # copy from the site
  post '/signup', to: 'registrations#signup'
  post '/signup2', to: 'registrations#login'

  # post '/login', to: 'sessions#login'
  get '/lgout', to: 'site#logout'
  get '/login_check', to: 'site#logged_in?'
  # end of copy
  namespace :api do
    namespace :v1 do
      get '/works', to: 'works#index'
      patch '/works/:id', to: 'works#update'
      get '/auth', to: 'sessions#login'
      post '/qrcode', to: 'works#create'
      # resources :todos, only: %i[index show create update destroy]
    end
  end

  # mapplic
  get '/map_json', to: 'site#map_json' # jsonfile for map
  get '/map/:map', to: 'site#map'

  # QrRead
  get 'qrread/index', to: 'site#index'
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :room, required: false

  after_create_commit { DirectMessageBroadJob.perform_later(self) }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/pickup_request.rb
class PickupRequest < ApplicationRecord
  has_many :receiveds
  has_many :work_schedules
  default_scope -> { order(pickup_date: :desc) }

  scope :search, lambda { |search_params|
    # search_paramsが空の場合以降の処理を行わない。
    # >> {}.blank?
    # => true
    return if search_params.blank?

    # パラメータを指定して検索を実行する
    car_type_is(search_params[:car_type])
      .date_from(search_params[:start_day])
      .date_to(search_params[:end_day])
    # それぞれのメソッドは↓で定義している
  }
  # awbが存在する場合、awbをlike検索する
  scope :car_type_is, ->(car_type) { where('car_type LIKE ?', "%#{car_type}%") if car_type.present? }
  scope :date_from, ->(from) { where('? <= pickup_date', from) if from.present? }
  scope :date_to, ->(to) { where('pickup_date <= ?', to) if to.present? }

  def total_order
    receiveds.all.sum(:number_of_order)
  end
end

app/models/received.rb
class Received < ApplicationRecord
  belongs_to :pickup_request, required: false

  default_scope -> { order(received_date: :desc) }

  scope :search, lambda { |search_params|
    # search_paramsが空の場合以降の処理を行わない。
    # >> {}.blank?
    # => true
    return if search_params.blank?

    # パラメータを指定して検索を実行する
    awb_is(search_params[:awb])
      .inv_is(search_params[:inv])
      .number_is(search_params[:number])
      .date_from(search_params[:start_day])
      .date_to(search_params[:end_day])
  }
  # awbが存在する場合、awbをlike検索する
  scope :awb_is, ->(awb) { where('awb LIKE ?', "%#{awb}%") if awb.present? }
  # invが存在する場合、invで検索する
  scope :inv_is, ->(inv) { where('invoice LIKE ?', "%#{inv}%") if inv.present? }
  # numberが存在する場合、invで検索する
  scope :number_is, ->(number) { where('number LIKE ?', "%#{number}%") if number.present? }
  # received_dateが存在する場合、received_dateで範囲検索する
  scope :date_from, ->(from) { where('? <= received_date', from) if from.present? }
  scope :date_to, ->(to) { where('received_date <= ?', to) if to.present? }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # validates :email, uniqueness: {case_sensitive: true}
  has_many :work_times
  before_create :qrno
  has_secure_password # bcryptの機能 attributeでpassword, passowrd_confirmationが自動生成, DBにはpassowrd_digestを作る必要がある
  validates :password, presence: true, length: { minimum: 4 }
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries

  def qrno
    self.qrcode = 7.times.map { SecureRandom.random_number(10) }.join.to_i
  end
end

app/models/work_schedule.rb
class WorkSchedule < ApplicationRecord
  belongs_to :pickup_request
  after_create :inputhours
  after_destroy :inputhours

  def inputhours
    pickup = pickup_request
    orders = pickup.total_order
    datas = pickup.work_schedules
    datas.each do |data|
      data.update_attribute(:hours, orders / datas.length)
    end
  end
end

app/models/work_time.rb
class WorkTime < ApplicationRecord
  belongs_to :user
  before_update :calhours

  def calhours
    update_column(:hours, (self.end - start) / 60) if self.end
  end
end

app/controllers/api/v1/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @received = Received.new
    @datas = Received.all
  end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
  def entried?(user)
    entries = user.entries.where(room_id: @room.id)
    if entries.empty?
      false
    else
      true
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/makepdfs_helper.rb
module MakepdfsHelper
end

app/helpers/qrcode_helper.rb
module QrcodeHelper
end

app/helpers/receiveds_helper.rb
module ReceivedsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !@current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/static_pages/index.html.erb
<h1 class="title">データ一覧</h1>

<div class="sub-title">
        <button class="make_button", id="received_button">クーリエ</button>
        <button class="make_button", id="pickup_request_button">航空貨物</button>    
        <!--mok_start-create-received-->
        <div class="received", style="display:none", id="received_form">
                
            <%= form_with model: @received , local: true do |f| %>
            
                <%= f.label :received_date, "日付" %>
                <%= f.date_field :received_date %>
                
                <%= f.label :awb %>
                <%= f.text_field :awb %>
                
                <%= f.label :invoice %>
                <%= f.text_field :invoice %>
                
                <%= f.label :inspection %>
                <%= f.check_box :inspection %>
                
                <%= f.label :shipping %>
                <%= f.check_box :shipping %>
                
                <%= f.label :number_of_order %>
                <%= f.text_field :number_of_order %>
                
                <%= f.label :shipping_date %>
                <%= f.date_field :shipping_date %>
                
                
                <%= f.submit %>
                
            <% end %>
        </div>
        <!--mok-start-create-pickup-->
        <div class="pickup_request", style="display:none", id="pickup_request_form">
            <%= form_with model: @pickup_request, local: true do |f| %>
            
                <%= f.label :pickup_date %>
                <%= f.date_field :pickup_date %>
                
                <%= f.label :type %>
                <%= f.text_field :type %>
                
                <%= f.label :number_of_car %>
                <%= f.text_field :number_of_car %>
                
                <%= f.label :weight %>
                <%= f.text_field :weight %>
                
                <%= f.label :arrange %>
                <%= f.check_box :arrange %>
                
                <%= f.label :car_number %>
                <%= f.text_field :car_number%>
                
                <%= f.label :received %>
                <%= f.check_box :received %>
                
                <%= f.label :number_of_total_order %>
                <%= f.text_field :number_of_total_order %>
                
                <%= f.submit "ボタン"%>
                
            <% end %>
            
            
            
        </div>
</div>
<!--mok-start-show-->

<div class="datas" >

    <div class="table table_box">
      <div class="tr_box tr_box_th">
        <div class="tr th received_data_column">入荷日</div>
        <div class="tr th awb-column">AWB</div>
        <div class="tr th invoice_column">INV</div>
        <div class="tr th thnumber_column">行数</div>
        <div class="tr th shipped_date_column">出荷日</div>
        <div class="tr th remark_column">備考</div>
        <div class="tr th function_column">機能</div>
      </div>
      <% @datas.each  do  |data|%>
      <div class="tr_box data_show tr_box_td" id=<%= "data_#{data["id"]}" %>>
        <div class="tr td received_data_row"><%= data["received_date"]%></div>
        <div class="tr td awb-row"><%= data["awb"]%></div>
        <div class="tr td invoice_row"><%= data["invoice"]%></div>
        <div class="tr td number_row"><%= data["number_of_order"]%></div>
        <div class="tr td shipped_date_row"><%= data["shipped_date"]%></div>
        <div class="tr td emark_column"></div>
        <div class="tr td function_row">
            <span><%= link_to "編集", receveds_modify_path(id: data["id"]), remote: true %></span>
        </div>
      </div>
      <%end%>
    </div>
    <%= link_to "PDF", pdf_path(format: "pdf") %>

  
</div>

app/views/static_pages/index_old1.html.erb
<h1 class="title">データ一覧</h1>

<div class="sub-title">
        <button class="make_button", id="received_button">クーリエ</button>
        <button class="make_button", id="pickup_request_button">航空貨物</button>    
        <!--mok_start-create-received-->
        <div class="received", style="display:none", id="received_form">
                
            <%= form_with model: @received , local: true do |f| %>
            
                <%= f.label :received_date, "日付" %>
                <%= f.date_field :received_date %>
                
                <%= f.label :awb %>
                <%= f.text_field :awb %>
                
                <%= f.label :invoice %>
                <%= f.text_field :invoice %>
                
                <%= f.label :inspection %>
                <%= f.check_box :inspection %>
                
                <%= f.label :shipping %>
                <%= f.check_box :shipping %>
                
                <%= f.label :number_of_order %>
                <%= f.text_field :number_of_order %>
                
                <%= f.label :shipping_date %>
                <%= f.date_field :shipping_date %>
                
                
                <%= f.submit %>
                
            <% end %>
        </div>
        <!--mok-start-create-pickup-->
        <div class="pickup_request", style="display:none", id="pickup_request_form">
            <%= form_with model: @pickup_request, local: true do |f| %>
            
                <%= f.label :pickup_date %>
                <%= f.date_field :pickup_date %>
                
                <%= f.label :arrange %>
                <%= f.check_box :arrange %>
                
                <%= f.label :car_number %>
                <%= f.text_field :car_number%>
                
                <%= f.label :received %>
                <%= f.check_box :received %>
                
                <%= f.label :number_of_total_order %>
                <%= f.text_field :number_of_total_order %>
                
                <%= f.submit "ボタン"%>
                
            <% end %>
            
            
            
        </div>
</div>
<!--mok-start-show-->

<div class="datas" >
    
    <ol>
    <% @datas.each  do  |data|%>
    
   <% if data["pickup_request_id"] == nil && data["pickup_requests_id"] == nil%>
        <li style="color:red;">
            <span class="reveiced_date">入荷予定日：<%= data["received_date"]%></span>
            <span class="awb">AWB：<%= data["awb"]%></span> 
            <span class="invoice">Inv：<%= data["invoice"]%></span> 
            <span class="inspection">検品：<%= data["inspection"]%></span> 
            <span class="shipping">出荷：<%= data["shipping"]%></span> 
            <span class="shipped_date">出荷日：<%= data["shipped_date"]%></span> 
            <span class="number_of_order">行数：<%= data["number_of_order"]%></span> 
        </li>
    
    <% else%>

    
       <li class="pickup_data" ,style="display: inline;">
            <span class="show_button"><%= link_to "▶︎", receiveds_show_path(id: data["pickup_requests_id"]), remote: true %></span>
            <span class="pickup_date">集荷日：<%= data["pickup_date"] %></span>
            <span class="arrange">手配：<%= data["arrange"] %></span>
            <span class="number_of_total_order">総行数：<%= data["number_of_total_order"] %></span>
      
        
        <!--mok-start-create-received-in-->
        <div class="pickup_request_form" id=<%= "pickup_data_#{data["id"]}_form" %>, style="display:none">
         <div id=<%= "receivedsin#{data["pickup_requests_id"]}"%>>
         </div>
            <div>
            <%= form_with model: @received , local: true do |f| %>
        
            <%= f.label :received_date, "日付" %>
            <%= f.date_field :received_date %>
            
            <%= f.label :awb %>
            <%= f.text_field :awb %>
            
            <%= f.label :invoice %>
            <%= f.text_field :invoice %>
            
            <%= f.label :inspection %>
            <%= f.check_box :inspection %>
            
            <%= f.label :shipping %>
            <%= f.check_box :shipping %>
            
            <%= f.label :number_of_order %>
            <%= f.text_field :number_of_order %>
            
            <%= f.label :shipping_date %>
            <%= f.date_field :shipping_date %>
            
            
            <%= f.submit %>
            <% end %>
            </div>
        </div>
        <!--mok-->
       </li>
        
       
    <% end %>
    <%end%>
    </ol>
</div>