config/routes.rb
Rails.application.routes.draw do
  # root "sessions#new"

  post 'direct_messages', to: 'direct_messages#create'
  resources :rooms
  resources :entries
  get 'events/work_hours', to: 'events#work_hours'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :work_schedules
  get 'works/edit', to: 'works#edit'
  patch 'works', to: 'works#update'
  # get 'works', to: "works#index"
  get 'works/data', to: 'works#data'
  get '/qrcode', to: 'qrcode#index'
  get 'cameras/index', to: 'cameras#index'
  get 'staffs/index'
  resources :users
  get 'events/index', to: 'events#index'
  get 'events/pickup', to: 'events#pickup'
  get 'events/received', to: 'events#received'

  get 'record_pdfs/index'

  get 'receiveds', to: 'receiveds#index'
  get 'receiveds/index_box', to: 'receiveds#index_box_in'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pickup_requests, only: %i[create update destroy]
  resources :receiveds, only: %i[create update destroy]
  post 'receiveds/update', to: 'receiveds#update'
  get '/receiveds/show', to: 'receiveds#show'
  get '/receveds/modify', to: 'receiveds#modify'
  get '/pdf', to: 'record_pdfs#index'
  get '/pickup_requests/index', to: 'pickup_requests#index'
  get 'pickup_requests/edit', to: 'pickup_requests#edit'
  post 'pickup_requests/create_received', to: 'pickup_requests#create_received'

  # ##########routes for react#############

  root to: redirect('/home')
  get '/home', to: 'site#index'
  get '/login_react', to: 'site#index'
  get '/dashboard', to: 'site#index'
  get '/works', to: 'site#index'

  # copy from the site
  post '/signup', to: 'registrations#signup'
  post '/signup2', to: 'registrations#login'

  # post '/login', to: 'sessions#login'
  get '/lgout', to: 'site#logout'
  get '/login_check', to: 'site#logged_in?'
  # end of copy
  namespace :api do
    namespace :v1 do
      get '/works', to: 'works#index'
      patch '/works/:id', to: 'works#update'
      get '/auth', to: 'sessions#login'
      post '/qrcode', to: 'works#create'
      # resources :todos, only: %i[index show create update destroy]
    end
  end

  # mapplic
  get '/map_json', to: 'site#map_json' # jsonfile for map
  get '/map/:map', to: 'site#map'

  # QrRead
  get 'qrread/index', to: 'site#index'
end

app/models/pickup_request.rb
class PickupRequest < ApplicationRecord
  has_many :receiveds
  has_many :work_schedules
  default_scope -> { order(pickup_date: :desc) }

  scope :search, lambda { |search_params|
    # search_paramsが空の場合以降の処理を行わない。
    # >> {}.blank?
    # => true
    return if search_params.blank?

    # パラメータを指定して検索を実行する
    car_type_is(search_params[:car_type])
      .date_from(search_params[:start_day])
      .date_to(search_params[:end_day])
    # それぞれのメソッドは↓で定義している
  }
  # awbが存在する場合、awbをlike検索する
  scope :car_type_is, ->(car_type) { where('car_type LIKE ?', "%#{car_type}%") if car_type.present? }
  scope :date_from, ->(from) { where('? <= pickup_date', from) if from.present? }
  scope :date_to, ->(to) { where('pickup_date <= ?', to) if to.present? }

  def total_order
    receiveds.all.sum(:number_of_order)
  end
end

app/controllers/pickup_requests_controller.rb
class PickupRequestsController < ApplicationController
  def index
    @pickup_request = PickupRequest.new
    @search_params = pickup_search_params
    @datasall = PickupRequest.search(@search_params)
    @datas = @datasall.page(params[:page]).per(20)
    respond_to do |format|
      format.html
      format.xlsx do
        # ファイル名をここで指定する（動的にファイル名を変更できる）
        @search_params = params[:data]
        @excels = PickupRequest.search(@search_params)
        response.headers['Content-Disposition'] = "attachment; filename=#{Date.today}.xlsx"
      end
    end
  end

  def create
    p = PickupRequest.new(pickup_params)
    p.save
    redirect_to pickup_requests_index_path
  end

  def create_received
    @pickup_data = PickupRequest.find_by(id: params[:id])
    @received_datas = @pickup_data.receiveds.all
    @received = @pickup_data.receiveds.build(pickup_params_receiveds)
    @received.save
  end

  def update
    @pickup_request = PickupRequest.find_by(id: params[:id])
    @pickup_request.update_attributes(pickup_params)
  end

  def destroy
    @pickup_request = PickupRequest.find_by(id: params[:id])
    @pickup_request.destroy
  end

  def edit
    @pickup_request = PickupRequest.find_by(id: params[:id])
  end

  def sendmail
    pickuprequest = PickupRequest.find_by(id: params[:id])
    PickupRequestMailer.send_pickup_request(pickuprequest).deliver
  end

  private

  def pickup_params
    params.require(:pickup_request).permit(:pickup_date, :arrange, :car_number,
                                           :received, :number_of_total_order, :number_of_car, :car_type, :weight, :cbm, :note, :ctn)
  end

  def pickup_params_receiveds
    params.require(:received).permit(:received_date, :awb, :invoice, :inspection,
                                     :shipping, :shipped_date, :number_of_order, :pickup_request_id, :number)
  end

  def pickup_search_params
    params.fetch(:search, {}).permit(:car_type, :start_day, :end_day)
  end
end

app/helpers/pickup_requests_helper.rb
module PickupRequestsHelper
end

app/views/pickup_requests/_edit.html.erb
      <%= form_with(model: @pickup_request, remote: true, class: "form_with_css") do |f| %>
                <div class="tr td pickup_date_row"><%= f.date_field :pickup_date %></div>
                <div class="tr td car_type_row"><%= f.text_field :car_type %></div>
                <div class="tr td number_of_car_row"><%= f.text_field :number_of_car %></div>
                <div class="tr td number_of_total_order_row"><%= @pickup_request.total_order %></div>
                <div class="tr td weight_row"><%= f.text_field :weight %></div>
                <div class="tr td cbm_row"><%= f.text_field :cbm %></div>
                <div class="tr td ctn_row"><%= f.text_field :ctn %></div>
                
                <div class="tr td remark_column"><%= f.text_field :note%></div>
                <div class="tr td function_row">
                    <span><%= f.submit "保存", class: "btn"%></span>
                   
                    <span><%= link_to "削除", pickup_request_path(id: @pickup_request.id), method: :delete, class: "btn", remote: true%></span>
                </div>
        <%end%>  
        

app/views/pickup_requests/_update.html.erb
        <div class="tr td pickup_date_row">
            <%= link_to "▶", receiveds_index_box_path(id: @pickup_request.id),  class: "btn-receiveds", remote: true %>
            <%= @pickup_request.pickup_date%>
        </div>
        <div class="tr td car_type_row"><%= @pickup_request.car_type%></div>
        <div class="tr td number_of_car_row"><%= @pickup_request.number_of_car%></div>
        <div class="tr td number_of_total_order_row"><%= @pickup_request.total_order%></div>
        <div class="tr td weight_row"><%= @pickup_request.weight%></div>
        <div class="tr td cbm_row"><%= @pickup_request.cbm%></div>
        <div class="tr td ctn_row"><%= @pickup_request.ctn%></div>
        
        <div class="tr td remark_column"><%= @pickup_request.note%></div>
        <div class="tr td function_row">
            <span><%= link_to "編集", pickup_requests_edit_path(id: @pickup_request.id), remote: true %></span>
            <span><%= link_to "PDF", pdf_path(format: :pdf, id: @pickup_request.id), local: true %></span>
            <span><%= link_to "●", work_schedules_path(id: @pickup_request.id), remote: true%></span>
        </div>

app/views/pickup_requests/create_received.js.erb
$("#data_<%= @pickup_data.id%>").next(".inside_table_box_background").html("<%= escape_javascript(render('/receiveds/index')) %>");

app/views/pickup_requests/destroy.js.erb
$("#data_<%= @pickup_request.id%>").remove();

app/views/pickup_requests/edit.js.erb
$("#data_<%= @pickup_request.id%>").html("<%= escape_javascript(render('/pickup_requests/edit')) %>");

app/views/pickup_requests/index.html.erb
<div class="page-title">
    <h1 class="title">集荷データ一覧</h1>
</div>
   
<!--mok-start-create-pickup-->
<div class="create-new-data", style="display:none", id="pickup_request_form">
    <div class="input-box">
    <i class="far fa-times-circle fa-lg closeicon"></i>
    <div class="pickup-title"><h2>集荷データ作成</h2></div>
    
    <%= form_with model: @pickup_request, class: "data-box", local: true do |f| %>
        <div class="pickup_date input-data">
            <%= f.label :pickup_date %>
            <%= f.date_field :pickup_date %>
        </div>   
        <div class="car_type input-data">
            <%= f.label :car_type %>
            <%= f.text_field :car_type %>
        </div>
        <div class="number_of_car input-data">
            <%= f.label :number_of_car %>
            <%= f.text_field :number_of_car %>
        </div>
        <div class="weight input-data">
            <%= f.label :weight %>
            <%= f.text_field :weight %>
        </div>
        <div class="cbm input-data">
            <%=f.label :cbm %>
            <%=f.text_field :cbm %>
        </div>
        <div class="ctn input-data">
            <%=f.label :ctn %>
            <%=f.text_field :ctn %>
        </div>
        <div class="note input-data">
            <%=f.label :note %>
            <%=f.text_field :note %>
        </div>
        <div class="number_of_total_order input-data">
            <%= f.label :number_of_total_order %>
            <%= f.text_field :number_of_total_order %>
        </div>
        <%= f.submit "作成", class: "btn" %>
        
    
        
    <% end %>
  
   </div> 
    
</div>
<!--search-box-->
<div class="search-box-container">
    
    <%= form_with scope: :search, url: '/pickup_requests/index', method: :get, local: true do |f| %>
    <%= f.date_field :start_day , class: "search-start-day"%>
    <span>〜</span>
    <%= f.date_field :end_day, class: "search-end-day" %>
    <%= f.label :car_type, "車種", class: "search-car-type"%>
    <%= f.text_field :car_type %>
    <%= f.submit '検索', class: "search-btn" %>
    <% end %>
</div>
<div class="pagination-box">
<%= paginate @datas%>
</div>
<div class="function-box">
    <div class="excel"><button class="make_button"><%= link_to "Excel出力", pickup_requests_index_path(data: @search_params, format: :xlsx) %></button></div>
    <div class="button-box-new">
        <button class="make_button", id="pickup_request_button">集荷データ作成</button> 
    </div>
</div>
<div class="datas" >

    <div class="table table_box">
      <div class="tr_box tr_box_th">
        <div class="tr th pickup_date">集荷日</div>
        <div class="tr th car_type">車種</div>
        <div class="tr th number_of_car">台数</div>
        <div class="tr th number_of_total_order">行数</div>
        <div class="tr th weight">重量</div>
        <div class="tr th cbm">CBM</div>
        <div class="tr th ctn">CTN</div>
        
        <div class="tr th remark_column">備考</div>
        <div class="tr th function_column">機能</div>
      </div>
      <% @datas.each  do  |data|%>
      <div class="tr_box data_show tr_box_td" id=<%= "data_#{data.id}" %>>
        <div class="tr td pickup_date_row">
            <%= link_to "▶", receiveds_index_box_path(id: data.id),  class: "btn-receiveds", remote: true %>
            <%= data.pickup_date%>
        </div>
        <div class="tr td car_type_row"><%= data.car_type%></div>
        <div class="tr td number_of_car_row"><%= data.number_of_car%></div>
        <div class="tr td number_of_total_order_row"><%= data.total_order%></div>
        <div class="tr td weight_row"><%= data.weight%></div>
        <div class="tr td cbm_row"><%= data.cbm %></div>
        <div class="tr td ctn_row"><%= data.ctn %></div>
        
        <div class="tr td remark_column"><%= data.note %></div>
        <div class="tr td function_row">
            <span><%= link_to "編集", pickup_requests_edit_path(id: data.id), remote: true %></span>
            <span><%= link_to "PDF", pdf_path(format: :pdf, id: data.id), local: true %></span>
            <span><%= link_to "●", work_schedules_path(id: data.id), remote: true%></span>
        </div>

      </div>
         <!--mok    showing revceiveds -->
        <div class="inside_table_box_background">

        </div>
      <%end%>
    </div>
</div>


<div class="work_back">
<div class="work_container">
<div class="work_schedules">
    <i class="far fa-times-circle fa-lg close"></i>
    <div class="title">作業日程</div>
    <div class="insert-box">
        
        <div class="workdates">
        </div>
    </div>
        
    </div>
    </div>
</div>

<script>
    $(".close").click(function(){
        $(".work_back").css('display', 'none');
    })
    
    $(".closeicon").click(function(){
        $("#pickup_request_form").css('display', 'none');
    })
</script>

app/views/pickup_requests/update.js.erb
$("#data_<%= @pickup_request.id%>").html("<%= escape_javascript(render('/pickup_requests/update')) %>");