config/routes.rb
Rails.application.routes.draw do
  # root "sessions#new"

  post 'direct_messages', to: 'direct_messages#create'
  resources :rooms
  resources :entries
  get 'events/work_hours', to: 'events#work_hours'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :work_schedules
  get 'works/edit', to: 'works#edit'
  patch 'works', to: 'works#update'
  # get 'works', to: "works#index"
  get 'works/data', to: 'works#data'
  get '/qrcode', to: 'qrcode#index'
  get 'cameras/index', to: 'cameras#index'
  get 'staffs/index'
  resources :users
  get 'events/index', to: 'events#index'
  get 'events/pickup', to: 'events#pickup'
  get 'events/received', to: 'events#received'

  get 'record_pdfs/index'

  get 'receiveds', to: 'receiveds#index'
  get 'receiveds/index_box', to: 'receiveds#index_box_in'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pickup_requests, only: %i[create update destroy]
  resources :receiveds, only: %i[create update destroy]
  post 'receiveds/update', to: 'receiveds#update'
  get '/receiveds/show', to: 'receiveds#show'
  get '/receveds/modify', to: 'receiveds#modify'
  get '/pdf', to: 'record_pdfs#index'
  get '/pickup_requests/index', to: 'pickup_requests#index'
  get 'pickup_requests/edit', to: 'pickup_requests#edit'
  post 'pickup_requests/create_received', to: 'pickup_requests#create_received'

  # ##########routes for react#############

  root to: redirect('/home')
  get '/home', to: 'site#index'
  get '/login_react', to: 'site#index'
  get '/dashboard', to: 'site#index'
  get '/works', to: 'site#index'

  # copy from the site
  post '/signup', to: 'registrations#signup'
  post '/signup2', to: 'registrations#login'

  # post '/login', to: 'sessions#login'
  get '/lgout', to: 'site#logout'
  get '/login_check', to: 'site#logged_in?'
  # end of copy
  namespace :api do
    namespace :v1 do
      get '/works', to: 'works#index'
      patch '/works/:id', to: 'works#update'
      get '/auth', to: 'sessions#login'
      post '/qrcode', to: 'works#create'
      # resources :todos, only: %i[index show create update destroy]
    end
  end

  # mapplic
  get '/map_json', to: 'site#map_json' # jsonfile for map
  get '/map/:map', to: 'site#map'

  # QrRead
  get 'qrread/index', to: 'site#index'
end

app/models/received.rb
class Received < ApplicationRecord
  belongs_to :pickup_request, required: false

  default_scope -> { order(received_date: :desc) }

  scope :search, lambda { |search_params|
    # search_paramsが空の場合以降の処理を行わない。
    # >> {}.blank?
    # => true
    return if search_params.blank?

    # パラメータを指定して検索を実行する
    awb_is(search_params[:awb])
      .inv_is(search_params[:inv])
      .number_is(search_params[:number])
      .date_from(search_params[:start_day])
      .date_to(search_params[:end_day])
  }
  # awbが存在する場合、awbをlike検索する
  scope :awb_is, ->(awb) { where('awb LIKE ?', "%#{awb}%") if awb.present? }
  # invが存在する場合、invで検索する
  scope :inv_is, ->(inv) { where('invoice LIKE ?', "%#{inv}%") if inv.present? }
  # numberが存在する場合、invで検索する
  scope :number_is, ->(number) { where('number LIKE ?', "%#{number}%") if number.present? }
  # received_dateが存在する場合、received_dateで範囲検索する
  scope :date_from, ->(from) { where('? <= received_date', from) if from.present? }
  scope :date_to, ->(to) { where('received_date <= ?', to) if to.present? }
end

app/controllers/receiveds_controller.rb
class ReceivedsController < ApplicationController
  def index
    @received = Received.new
    @search_params = received_search_params
    @datas = Received.search(@search_params).page(params[:page]).per(20)
    respond_to do |format|
      format.html
      format.xlsx do
        # ファイル名をここで指定する（動的にファイル名を変更できる）
        @search_params = params[:data]
        @excels = Received.search(@search_params)
        response.headers['Content-Disposition'] = "attachment; filename=#{Date.today}.xlsx"
      end
    end
  end

  def index_box_in
    @pickup_data = PickupRequest.find_by(id: params[:id])
    @received_datas = @pickup_data.receiveds.all
    @received = @pickup_data.receiveds.build
  end

  def create
    p = PickupRequest.find_by(id: params[:id])
    if p.nil?

      r = Received.new(received_params)
      r.save
      redirect_to receiveds_path
    else

      r = p.Received.build(received_params)
      r.save

      redirect_to receiveds_path
    end
  end

  def show
    @pickup_data = PickupRequest.find_by(id: params[:id].to_i)
    @receivedsin = @pickup_data.receiveds
  end

  def modify
    @received = Received.find_by(id: params[:id])
  end

  def update
    @received = Received.find_by(id: params[:id])
    @received.update_attributes(received_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @data = Received.find_by(id: params[:id])
    @data.destroy
  end

  private

  def received_params
    params.require(:received).permit(:received_date, :awb, :invoice, :inspection,
                                     :shipping, :shipped_date, :number_of_order, :pickup_request_id, :number)
  end

  def received_search_params
    params.fetch(:search, {}).permit(:awb, :inv, :start_day, :end_day, :number)
  end
end

app/helpers/receiveds_helper.rb
module ReceivedsHelper
end

app/views/receiveds/_destroy.html.erb
        <div class="tr td received_data_row"><%= @data.received_date%></div>
        <div class="tr td number_row"><%= @data.number%></div>
        <div class="tr td awb-row"><%= @data.awb%></div>
        <div class="tr td invoice_row"><%= @data.invoice%></div>
        <div class="tr td number_row"><%= @data.number_of_order%></div>
        <div class="tr td shipped_date_row"><%= @data.shipped_date%></div>
        <div class="tr td emark_column"></div>
        <div class="tr td function_row">
            <span><%= link_to "編集", receveds_modify_path(id: @data.id), remote: true %></span>
        </div>

app/views/receiveds/_index.html.erb
<div class="inside_table_box">
              
    <div class="inside_tr_th">
         <div class="intr inth received_data_column">入荷日</div>
         <div class="intr inth number_column">入荷予定No</div>
         <div class="intr inth awb-column">AWB</div>
         <div class="intr inth invoice_column">INV</div>
         <div class="intr inth thnumber_column">行数</div>
         <div class="intr inth shipped_date_column">出荷日</div>
         <div class="intr inth remark_column">備考</div>
         <div class="intr inth function_column">機能</div>
     </div>
     <div class="inside_tr_td" >
          <%= form_with(url: pickup_requests_create_received_path(id: @received.pickup_request.id),scope: :received, method: :post, remote: true, class: "form_with_css") do |f| %>
                    <div class="tr td received_data_row"><%= f.date_field :received_date %></div>
                    <div class="tr td number_row"><%= f.text_field :number %></div>
                    <div class="tr td awb-row"><%= f.text_field :awb %></div>
                    <div class="tr td invoice_row"><%= f.text_field :invoice %></div>
                    <div class="tr td number_row"><%= f.text_field :number_of_order %></div>
                    <div class="tr td shipped_date_row"><%= f.date_field :shipped_date %></div>
                    <div class="tr td emark_column"></div>
                    <div class="tr td function_row">
                        <span><%= f.submit "保存", class: "btn"%></span>
                        
                    </div>
            <%end%>  
     </div>
     <% @received_datas.each  do  |data|%>
          <div class="inside_tr_td" id=<%= "data_re_#{data.id}" %>>
            <div class="intr intd received_data_row"><%= data.received_date%></div>
            <div class="intr intd number?row"><%= data.number%></div>
            <div class="intr intd awb-row"><%= data.awb%></div>
            <div class="intr intd invoice_row"><%= data.invoice%></div>
            <div class="intr intd number_row"><%= data.number_of_order%></div>
            <div class="intr intd shipped_date_row"><%= data.shipped_date%></div>
            <div class="intr intd emark_column"></div>
            <div class="intr intd function_row">
                <span><%= link_to "編集", receveds_modify_path(id: data.id), remote: true %></span>
            </div>
          </div>
     <%end%>
 
 </div>

app/views/receiveds/_modify.html.erb
        <%= form_with(model: @received, remote: true, class: "form_with_css") do |f| %>
                <div class="tr td received_data_row"><%= f.date_field :received_date %></div>
                <div class="tr td number_row"><%= f.text_field :number %></div>
                <div class="tr td awb-row"><%= f.text_field :awb %></div>
                <div class="tr td invoice_row"><%= f.text_field :invoice %></div>
                <div class="tr td number_row"><%= f.text_field :number_of_order %></div>
                <div class="tr td shipped_date_row"><%= f.date_field :shipped_date %></div>
                <div class="tr td emark_column">
                </div>
                <div class="tr td function_row">
                <span>
                    <%= f.submit "保存", class: "btn"%>
                </span>
                    <span ><%= link_to("削除", received_path(@received.id),class: "btn",method: :delete , remote: true)%></span>
                </div>
        <%end%>
       
        

app/views/receiveds/_receivedsin.html.erb
<% if @receivedsin %>
            
     <% @receivedsin.each do |received| %>
     <li>
            <span class="reveiced_date">入荷予定日：<%= received.received_date%></span>
            <span class="number">入荷予定No：<%= received.number %></span> 
            <span class="awb">AWB：<%= received.awb %></span> 
            <span class="invoice">Inv：<%= received["invoice"]%></span> 
            <span class="inspection">検品：<%= received.inspection %></span> 
            <span class="shipping">出荷：<%= received.shipping%></span> 
            <span class="shipped_date">出荷日：<%= received.shipped_date%></span> 
            <span class="number_of_order">行数：<%= received.number_of_order %></span> 
     </li>
     <%end%>
<%end%>

app/views/receiveds/_update.html.erb
        <div class="tr td received_data_row"><%= @received.received_date%></div>
        <div class="tr td number-row"><%= @received.number%></div>
        <div class="tr td awb-row"><%= @received.awb%></div>
        <div class="tr td invoice_row"><%= @received.invoice%></div>
        <div class="tr td number_row"><%= @received.number_of_order%></div>
        <div class="tr td shipped_date_row"><%= @received.shipped_date %></div>
        <div class="tr td emark_column">
            <% if  pickup_exist?(@received.id)%>
            <%= "航空便　" %>
            <% else %>
            <%= "クーリエ" %>
            <% end %>
            
        </div>
        <div class="tr td function_row">
            <span><%= link_to "編集", receveds_modify_path(id: @received.id), remote: true %></span>
        </div>

app/views/receiveds/_update2.html.erb
<%= @received.pickup_request.total_order %>

app/views/receiveds/destroy.js.erb
$("#data_re_<%= @data.id%>").remove();

app/views/receiveds/index.html.erb
<div class="page-title">
    <h1 class="title">クーリエデータ一覧</h1>
</div>

<!--mok_start-create-received-->
<div class="create-new-data", style="display:none", id="pickup_request_form">
    <div class="input-box">
        <i class="far fa-times-circle fa-lg closeicon"></i>
        <div class="pickup-title"><h2>クーリエデータ作成</h2></div>
        
        <%= form_with model: @received , class: "data-box", local: true do |f| %>
        <div class=" input-data">
            <%= f.label :received_date, "日付" %>
            <%= f.date_field :received_date %>
        </div>
        <div class=" input-data">
            <%= f.label :awb %>
            <%= f.text_field :awb %>
        </div>
        <div class=" input-data">
            <%= f.label :invoice %>
            <%= f.text_field :invoice %>
        </div>
        <div class=" input-data">
            <%= f.label :number %>
            <%= f.text_field :number %>
        </div>
        <div class=" input-data">
            <%= f.label :number_of_order %>
            <%= f.text_field :number_of_order %>
        </div>    
        <div class=" input-data">
            <%= f.label :shipping_date %>
            <%= f.date_field :shipping_date %>
        </div>
            
            <%= f.submit "作成", class: "btn" %>
            
        <% end %>
    </div>
</div>
<div class="search-box-container">
    <%= form_with url: receiveds_path, scope: :search, local: true, method: :get do |f| %>
    <%= f.date_field :start_day , class: "search-start-day"%>
    <span>〜</span>
    <%= f.date_field :end_day, class: "search-end-day" %>
    <%= f.label :number, "入荷予定No", class: "search-car-type"%>
    <%= f.text_field :number %>
    <%= f.label :awb, "AWB", class: "search-car-type"%>
    <%= f.text_field :awb %>
    <%= f.label :inv, "INV", class: "search-car-type"%>
    <%= f.text_field :inv %>
    
    <%= f.submit '検索', class: "search-btn" %>
    <% end %>
    
</div>
<!--mok-start-show-->
<div class="pagination-box">
<%= paginate @datas%>
</div>
<div class="function-box">
    <div class="excel"><button class="make_button"><%= link_to "Excel出力", receiveds_path(data: @search_params, format: :xlsx) %></button></div>
    <div class="button-box-new">
       <button class="make_button", id="received_button">入荷予定</button> 
    </div>
</div>

<div class="datas" >

    <div class="table table_box">
      <div class="tr_box tr_box_th">
        <div class="tr th received_data_column">入荷日</div>
        <div class="tr th number=column">入荷予定No</div>
        <div class="tr th awb-column">AWB</div>
        <div class="tr th invoice_column">INV</div>
        <div class="tr th thnumber_column">行数</div>
        <div class="tr th shipped_date_column">出荷日</div>
        <div class="tr th remark_column">備考</div>
        <div class="tr th function_column">機能</div>
      </div>
      <% @datas.each  do  |data|%>
      <div class="tr_box data_show tr_box_td" id=<%= "data_re_#{data["id"]}" %>>
        <div class="tr td received_data_row"><%= data["received_date"]%></div>
        <div class="tr td number_row"><%= data["number"]%></div>
        <div class="tr td awb-row"><%= data["awb"]%></div>
        <div class="tr td invoice_row"><%= data["invoice"]%></div>
        <div class="tr td number_row"><%= data["number_of_order"]%></div>
        <div class="tr td shipped_date_row"><%= data["shipped_date"]%></div>
        <div class="tr td emark_column">
        <% if  pickup_exist?(data.id)%>
        <%= "航空便　" %>
        <% else %>
        <%= "クーリエ" %>
        <% end %>
        
        </div>
        <div class="tr td function_row">
            <span><%= link_to "編集", receveds_modify_path(id: data["id"]), remote: true %></span>
        </div>
      </div>
      <%end%>
    </div>

  
</div>

<script>
    
    $(".closeicon").click(function(){
        $("#pickup_request_form").css('display', 'none');
    })
</script>

app/views/receiveds/index_box_in.js.erb
$("#data_<%= @pickup_data.id%>").next('.inside_table_box_background').html("<%= escape_javascript(render('/receiveds/index')) %>");

app/views/receiveds/modify.js.erb
$("#data_re_<%= @received.id%>").html("<%= escape_javascript(render('/receiveds/modify')) %>");

app/views/receiveds/show.js.erb
$("#receivedsin<%= @pickup_data.id%>").html("<%= escape_javascript(render('/receiveds/receivedsin')) %>");

app/views/receiveds/update.js.erb
$("#data_re_<%= @received.id%>").html("<%= escape_javascript(render('/receiveds/update')) %>");


<% if @received.pickup_request_id != nil %>
    $("#data_<%= @received.pickup_request_id%>").find('.number_of_total_order_row').html("<%= escape_javascript(render('/receiveds/update2')) %>");
<% end %>