config/routes.rb
Rails.application.routes.draw do
  # root "sessions#new"

  post 'direct_messages', to: 'direct_messages#create'
  resources :rooms
  resources :entries
  get 'events/work_hours', to: 'events#work_hours'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :work_schedules
  get 'works/edit', to: 'works#edit'
  patch 'works', to: 'works#update'
  # get 'works', to: "works#index"
  get 'works/data', to: 'works#data'
  get '/qrcode', to: 'qrcode#index'
  get 'cameras/index', to: 'cameras#index'
  get 'staffs/index'
  resources :users
  get 'events/index', to: 'events#index'
  get 'events/pickup', to: 'events#pickup'
  get 'events/received', to: 'events#received'

  get 'record_pdfs/index'

  get 'receiveds', to: 'receiveds#index'
  get 'receiveds/index_box', to: 'receiveds#index_box_in'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pickup_requests, only: %i[create update destroy]
  resources :receiveds, only: %i[create update destroy]
  post 'receiveds/update', to: 'receiveds#update'
  get '/receiveds/show', to: 'receiveds#show'
  get '/receveds/modify', to: 'receiveds#modify'
  get '/pdf', to: 'record_pdfs#index'
  get '/pickup_requests/index', to: 'pickup_requests#index'
  get 'pickup_requests/edit', to: 'pickup_requests#edit'
  post 'pickup_requests/create_received', to: 'pickup_requests#create_received'

  # ##########routes for react#############

  root to: redirect('/home')
  get '/home', to: 'site#index'
  get '/login_react', to: 'site#index'
  get '/dashboard', to: 'site#index'
  get '/works', to: 'site#index'

  # copy from the site
  post '/signup', to: 'registrations#signup'
  post '/signup2', to: 'registrations#login'

  # post '/login', to: 'sessions#login'
  get '/lgout', to: 'site#logout'
  get '/login_check', to: 'site#logged_in?'
  # end of copy
  namespace :api do
    namespace :v1 do
      get '/works', to: 'works#index'
      patch '/works/:id', to: 'works#update'
      get '/auth', to: 'sessions#login'
      post '/qrcode', to: 'works#create'
      # resources :todos, only: %i[index show create update destroy]
    end
  end

  # mapplic
  get '/map_json', to: 'site#map_json' # jsonfile for map
  get '/map/:map', to: 'site#map'

  # QrRead
  get 'qrread/index', to: 'site#index'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @messages = DirectMessage.all
    @message = DirectMessage.new
    @entries = @user.entries
    @room = @user.rooms.new
  end

  def show
    @room = Room.find_by(id: params[:id])
    @messages = @room.direct_messages.all
    @message = current_user.direct_messages.new
    @entry = @room.entries.new
    gon.room_id = @room.id
    @users = User.all
  end

  def create
    @room = Room.new(name: params[:room][:name])
    if @room.valid?
      @room.save
      @entry = current_user.entries.new(room_id: @room.id)
      @entry.save
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_create.html.erb
 <div class="entry">
  <div class="room-name">
     <%= link_to @entry.room.name, room_path(@entry.room), data: {"turbolinks" => false} %>
  </div>
  
  <div class="room-users">
   <div class="room-user">
    Users:
    <% @entry.room.entries.each do |entry| %>
    <span class="user-names"><%= entry.user.name %></span>
     <% end %>
    </div>
      
    
  </div>
 </div>

app/views/rooms/_entries.html.erb
 <div class="entry">
  <div class="room-name">
     <%= link_to entry.room.name, room_path(entry.room), data: {"turbolinks" => false} %>
  </div>
  
  <div class="room-users">
   <div class="room-user">
    Users:
    <% entry.room.entries.each do |entry| %>
    <span class="user-names"><%= entry.user.name %></span>
     <% end %>
    </div>
      
    
  </div>
 </div>

app/views/rooms/create.js.erb
$("<%= escape_javascript(render('/rooms/create')) %>").appendTo('#chatbox');

app/views/rooms/index.html.erb
<div class="page-title">
    <h1 class="title">チャットルーム一覧</h1>
</div>

<div class="chat-shows-containers">
    <div class="chat-rooms", id="chatbox">
        <% @entries.each do |entry| %>
         <%= render 'rooms/entries' , entry: entry %>
        <% end %>
    </div>
</div>
<%= form_with model: @room , method: :post do |f| %>
    <div class="chat-new input-group mb-3">
        <%= f.text_field :name, placeholder: "create new room!", class: "form-control" %>
    
        <div class="input-group append">
            <%= f.submit "Send", class: "btn btn-primary" %>
        </div>
        
    </div>
<%end%>

app/views/rooms/show.html.erb
<div class="page-title">
    <h1 class="title">チャットルーム</h1>
</div>
<div class="add-user-container">
    <div class="button-box-new">
        <button class="make_button", id="pickup_request_button">ユーザーを招待</button> 
    </div>
</div>
<div class="chat-container">
    <div class="chat-box", id="chatbox">
        <% @messages.each do |message| %>
         <%= render 'messages/messages' , message: message %>
        <% end %>
    </div>
</div>
<%= form_with model: @message , method: :post do |f| %>
<div class="chat-new input-group mb-3">
    <%= f.text_field :content, placeholder: "Say Something...", class: "form-control" %>
    <%= f.hidden_field :room_id, value: @room.id %>
    
    <div class="input-group append">
        <%= f.submit "Send", class: "btn btn-primary" %>
    </div>
</div>
<%end%>

<div class="invite-users create-new-data", id="pickup_request_form">
    <div class="input-box">
    <i class="far fa-times-circle fa-lg closeicon"></i>
    <%= form_with model: @entry , data: { remote: false }, method: :post do |f| %>
    <div class="input-group mb-3">
        <% @users.each do |user| %>
            <% if !entried?(user) %>
                <div class="users-chat">
                <p class="check-box-user"><%= user.name %></p>
                <%= f.check_box :user_ids,  { multiple: true}, user.id, nil%>
                </div>
            <%end%>
        <% end %>
                <%= f.hidden_field :room_id, value: @room.id %>
            <div class="input-group append">
                <%= f.submit "Invite", class: "btn btn-primary closeicon" %>
            </div>
            </div>
        <%end%>
        
        <h4> 参加者 ↓</h4>
        <% @users.each do |user| %>
            <% if entried?(user) %>
                
                <div class="check-box-user"><%= user.name %></div>
        
                
            <%end%>
        <% end %>

</div>
</div>



<script>

    
    $(".closeicon").click(function(){
        $("#pickup_request_form").css('display', 'none');
    })
</script>